languageCode = 'pl-PL'
title = 'yaktoMedia'
theme = "nightfall"

[params]
hostname = "yakto.eu"
footerHtml = 'YakToMedia!?'

[params.author]
name = "Szymon Kosmowski"
email = "hugo@example.com"

[[params.social]]
key = 1
name = "instagram"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "filmpolski"
url = "https://www.example.com"
rel = "me"                      # You can also add rel to social link

[[params.social]]
key = 3
name = "team4set"
url = "mailto:email@example.com"

[menu]
[[menu.header]]
name = "nowe"
weight = 1
url = "/posts"

[[menu.header]]
name = "o:mnie"
weight = 2
url = "/about-me"

[[menu.header]]
name = "moje:prace"
weight = 3
url = "/tags/"

[[menu.header]]
name = "kontakt"
weight = 4
url = "/categories/"
