languageCode = 'en-EN'
title = 'YakTo'
theme = "nightfall"

[params]
user = 'ksmvsky'
hostname = "yakto.eu"
footerHtml = 'Instagram - FilmPolski - FaceBook'
readingTime = false
color = "orange"

[params.author]
name = "Szymon Kosmowski"
url = "/about"

[[params.social]]
name = "Advertisment"
url = "/categories/advertisement"

[[params.social]]
name = "Film"
url = "/categories/film"

[[params.social]]
name = "Music"
url = "/categories/music"

[[params.social]]
name = "Selfmade"
url = "/categories/selfmade"

[[params.social]]
name = "Short"
url = "/categories/short/"

[[params.social]]
name = "Videoclip"
url = "/categories/videoclip"


[menu]

[[menu.header]]
name = "about"
weight = 1
url = "/about"

[[menu.header]]
name = "new"
weight = 2
url = "/posts"

[[menu.header]]
name = "tags"
weight = 3
url = "/tags/"

[[menu.header]]
name = "hire"
weight = 4
url = "/hire"
